version: "0.11"
units: meters
meshes:
  - id: walls
    primitives:
      - macro: box_decompose
        id: front
        mesh: walls
        axis: x
        span: [0.0, 10.0]
        base_y: 0.0
        height: 3.0
        thickness: 0.2
        cutouts:
          - id: door
            span: [2.0, 3.0]
            bottom: 0.0
            top: 2.1
          - id: win
            span: [6.0, 8.0]
            bottom: 0.8
            top: 2.0
